# Generated by Django 4.2.3 on 2023-08-17 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bar_code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('availabile', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('floor_Count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('floor', models.IntegerField()),
                ('code', models.CharField(max_length=20)),
                ('building_id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lib_app.building')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=50)),
                ('phone_number', models.CharField(max_length=12)),
                ('email', models.CharField(max_length=25)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=50)),
                ('self_number', models.IntegerField()),
                ('department_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.department')),
            ],
        ),
        migrations.CreateModel(
            name='Issuence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_date', models.DateField()),
                ('retuen_date', models.DateField()),
                ('status', models.CharField(max_length=20)),
                ('Admin_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib_app.admin')),
                ('issued_book_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib_app.books')),
                ('member_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='books',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lib_app.section'),
        ),
    ]
