# Generated by Django 4.2.4 on 2023-09-08 10:30

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('lib_app', '0002_subscription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('time_stamp', models.DateTimeField()),
                ('amount', models.IntegerField()),
                ('method', models.CharField(max_length=20)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib_app.admin')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lib_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='subscription',
            name='transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='lib_app.transaction'),
        ),
    ]
